//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: P2PControlMsg.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"P2PControlReq")]
  public partial class P2PControlReq : global::ProtoBuf.IExtensible
  {
    public P2PControlReq() {}
    
    private protocol.P2PControlReq.MsgFrom _msgFrom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgFrom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.P2PControlReq.MsgFrom msgFrom
    {
      get { return _msgFrom; }
      set { _msgFrom = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private protocol.P2PControlReq.Command _command;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.P2PControlReq.Command command
    {
      get { return _command; }
      set { _command = value; }
    }

    private string _filename = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string filename
    {
      get { return _filename; }
      set { _filename = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MsgFrom")]
    public enum MsgFrom
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER", Value=0)]
      SERVER = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PC", Value=1)]
      PC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APP", Value=2)]
      APP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Command")]
    public enum Command
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"START", Value=0)]
      START = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP", Value=1)]
      STOP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STARTALL", Value=2)]
      STARTALL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOPALL", Value=3)]
      STOPALL = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"P2PControlRsp")]
  public partial class P2PControlRsp : global::ProtoBuf.IExtensible
  {
    public P2PControlRsp() {}
    
    private protocol.P2PControlRsp.MsgFrom _msgFrom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgFrom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.P2PControlRsp.MsgFrom msgFrom
    {
      get { return _msgFrom; }
      set { _msgFrom = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private protocol.P2PControlRsp.Status _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.P2PControlRsp.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MsgFrom")]
    public enum MsgFrom
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER", Value=0)]
      SERVER = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PC", Value=1)]
      PC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APP", Value=2)]
      APP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Status")]
    public enum Status
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}