//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PCKeepAliveMsg.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PCKeepAlivePacket")]
  public partial class PCKeepAlivePacket : global::ProtoBuf.IExtensible
  {
    public PCKeepAlivePacket() {}
    
    private protocol.PCKeepAlivePacket.KeepAliveType _keepAliveType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"keepAliveType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.PCKeepAlivePacket.KeepAliveType keepAliveType
    {
      get { return _keepAliveType; }
      set { _keepAliveType = value; }
    }

    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"KeepAliveType")]
    public enum KeepAliveType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}